@baseUrl = http://localhost:8800/api/v1

### 1. Получить информацию о модели
GET {{baseUrl}}/model_info
Content-Type: application/json

### 2. Сделать предсказание (BASE модель) Правильный ответ 1
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"ZpYIoDJMcFzVoPFsHGJL",
  "utm_medium":"banner",
  "device_brand":"Huawei",
  "visit_number":1,
  "utm_campaign":"LEoPHuyFvzoNfnzGgfcd",
  "utm_keyword":"puhZPIYqKXeFPaUviSjo"
}

###

POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"ZpYIoDJMcFzVoPFsHGJL",
  "utm_medium":"banner",
  "device_brand":"Xiaomi",
  "visit_number":1,
  "utm_campaign":"SgIUDYUKnyWHVowUOqid",
  "utm_keyword":"unknown"
}

###

POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"kjsLglQLzykiRbcDiGcD",
  "utm_medium":"cpc",
  "device_brand":"Apple",
  "visit_number":3,
  "utm_campaign":"unknown",
  "utm_keyword":"unknown"
}

###

POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"bByPQxmDaMXgpHeypKSM",
  "utm_medium":"referral",
  "device_brand":"",
  "visit_number":1,
  "utm_campaign":"LTuZkdKfxRGVceoWkVyg",
  "utm_keyword":"unknown"
}

###

POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"kjsLglQLzykiRbcDiGcD",
  "utm_medium":"cpc",
  "device_brand":"Asus",
  "visit_number":1,
  "utm_campaign":"bJJuEXRheRIxXEaYIXqM",
  "utm_keyword":"unknown"
}

### 2. Сделать предсказание (BASE модель) Правильный ответ 0
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"fgymSoTvjKPEgaIJqsiH",
  "utm_medium":"cpm",
  "device_brand":"unknown",
  "visit_number":1,
  "utm_campaign":"FTjNLDyTrXaWYgZymFkV",
  "utm_keyword":"qUcotcWimEOQiboVPcCx"
}

###
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"fDLlAcSmythWSCVMvqvL",
  "utm_medium":"(none)",
  "device_brand":"Apple",
  "visit_number":2,
  "utm_campaign":"LTuZkdKfxRGVceoWkVyg",
  "utm_keyword":"unknown"
}

###
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"fDLlAcSmythWSCVMvqvL",
  "utm_medium":"(none)",
  "device_brand":"",
  "visit_number":1,
  "utm_campaign":"LTuZkdKfxRGVceoWkVyg",
  "utm_keyword":"unknown"
}

###
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"fDLlAcSmythWSCVMvqvL",
  "utm_medium":"(none)",
  "device_brand":"Xiaomi",
  "visit_number":1,
  "utm_campaign":"LTuZkdKfxRGVceoWkVyg",
  "utm_keyword":"unknown"
}

###
POST {{baseUrl}}/predict
Content-Type: application/json

{
  "utm_source":"fDLlAcSmythWSCVMvqvL",
  "utm_medium":"(none)",
  "device_brand":"",
  "visit_number":1,
  "utm_campaign":"LTuZkdKfxRGVceoWkVyg",
  "utm_keyword":"unknown"
}

### 1. Получить значения фичей
GET {{baseUrl}}/features
Content-Type: application/json